//! PostgreSQL populator for load testing.
//!
//! This crate provides functionality to populate PostgreSQL databases with test data
//! generated by the loadtest-generator crate.
//!
//! # Example
//!
//! ```ignore
//! use loadtest_postgresql::PostgreSQLPopulator;
//! use sync_core::SyncSchema;
//!
//! let schema = SyncSchema::from_yaml("path/to/schema.yaml")?;
//! let mut populator = PostgreSQLPopulator::new(
//!     "postgresql://postgres:postgres@localhost:5432/testdb",
//!     schema,
//!     42,
//! ).await?;
//!
//! // Create table and populate with 1000 rows
//! populator.create_table("users").await?;
//! let metrics = populator.populate("users", 1000).await?;
//! ```

pub mod args;
mod error;
mod insert;
mod populator;

pub use args::{CommonPopulateArgs, PostgreSQLPopulateArgs};
pub use error::PostgreSQLPopulatorError;
pub use populator::{PopulateMetrics, PostgreSQLPopulator};
