//! MongoDB populator for load testing.
//!
//! This crate provides functionality to populate MongoDB databases with test data
//! generated by the loadtest-generator crate.
//!
//! # Example
//!
//! ```ignore
//! use loadtest_mongodb::MongoDBPopulator;
//! use sync_core::Schema;
//!
//! let schema = Schema::from_yaml("path/to/schema.yaml")?;
//! let mut populator = MongoDBPopulator::new(
//!     "mongodb://root:root@localhost:27017",
//!     "testdb",
//!     schema,
//!     42,
//! ).await?;
//!
//! // Populate collection with 1000 documents
//! let metrics = populator.populate("users", 1000).await?;
//! ```

pub mod args;
mod error;
mod insert;
mod populator;

pub use args::{CommonPopulateArgs, MongoDBPopulateArgs};
pub use error::MongoDBPopulatorError;
pub use populator::{MongoDBPopulator, PopulateMetrics};
