//! MySQL populator for load testing.
//!
//! This crate provides functionality to populate MySQL databases with test data
//! generated by the loadtest-generator crate.
//!
//! # Example
//!
//! ```ignore
//! use loadtest_mysql::MySQLPopulator;
//! use sync_core::Schema;
//!
//! let schema = Schema::from_yaml("path/to/schema.yaml")?;
//! let mut populator = MySQLPopulator::new("mysql://root:root@localhost:3306/testdb", schema, 42).await?;
//!
//! // Create table and populate with 1000 rows
//! populator.create_table("users").await?;
//! let metrics = populator.populate("users", 1000).await?;
//! ```

pub mod args;
mod error;
mod insert;
mod populator;

pub use args::{CommonPopulateArgs, MySQLPopulateArgs};
pub use error::MySQLPopulatorError;
pub use populator::{MySQLPopulator, PopulateMetrics};
